//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SPU3AutoIPConfigTool.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_SPU3_DEVICE_FORM            101
#define IDS_EXIT_APPLICATION            101
#define IDS_APP_VERSION_NUM             102
#define IDD_DIALOGBAR                   103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_ALL_DEVICES_FORM            104
#define IDD_MAIN_FORM                   105
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_SPU3AutoIPConfiTYPE         130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_REFRESH_TREE                 143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_TREE                        171
#define IDB_TREE_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDC_DEVICE_TREE_CTRL            183
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define ID_STATUS_BAR_MSG_PANE          310
#define IDB_BITMAP_LOAD                 329
#define IDB_BITMAP_REPORT               330
#define IDB_BITMAP_HISTORY              331
#define IDB_BITMAP_REBOOT               332
#define IDB_BITMAP_BLINK_LED            333
#define IDB_BITMAP_APPLY                334
#define IDB_BITMAP_BLINK_LED_NOTACTIVE  335
#define IDC_LOAD_BUTTON                 1000
#define IDC_XML_FILE_BROWSE             1001
#define IDC_STATIC_SPU3_DEVICE_SETTINGS 1002
#define IDC_IPADDRESS_SPU3              1003
#define IDC_CHECK_CHG_SPU3_IPADDR_TO    1004
#define IDC_COMBO_CHG_SPU3_IPADDR_TO    1005
#define IDC_SUBNET_MASK_SPU3            1006
#define IDC_COMBO_SPU3_COMM_TYPE        1007
#define IDC_EDIT_SPU3_FW_VERSION        1008
#define IDC_COMBO_SPU3_PORT_ORIENTATION 1009
#define IDC_CHECK_ENABLE_PERFORMANCE_MODE 1010
#define IDC_BUTTON_REBOOT_SPU3          1011
#define IDC_IPADDRESS_MERCURY_SERVER    1012
#define IDC_EDIT_SOCK_PORT              1013
#define IDC_BUTTON3                     1014
#define IDC_BUTTON_APPLY_CHANGES        1014
#define IDC_STATIC_SPU_NAME             1018
#define IDC_LIST_PORT_INKERS            1019
#define IDC_MFCBUTTON1                  1020
#define IDC_BTN_GENERATE_REPORT         1020
#define IDC_BTN_CREATE_HIST_FILE        1021
#define IDC_CHECK2                      1022
#define IDC_CHECK__BLINK_SPU3_LEDS      1022
#define IDC_STATIC_HOST_WINDOW          1024
#define IDC_LIST_SPU3_DEVICES           1026
#define IDC_STATIC_SERVER_SETTINGS      1027
#define IDC_STATIC_REPORT_GROUP_BOX     1028
#define IDC_REPORT_FOLDER_BROWSE        1029
#define IDC_STATIC_VERSION              1030
#define IDC_STATIC_COPY_RIGHTS          1031
#define ID_BUTTON32773                  32773
#define ID_FILE_PRINT                   0xE107

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        330
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           311
#endif
#endif
